baseURL = 'https://magics0ng-github-io.pages.dev'
languageCode = 'zh-cn'
title = 'Krisçš„Neverland'
theme = 'PaperMod'
defaultContentLanguage = 'zh'
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = [ "posts", "papermod" ]
[minify]
disableXML = true
[languages.zh]
languageName = "Chinese"
weight = 1
  [languages.zh.taxonomies]
  tag = "tags"
  archives="archives"
[[languages.zh.menu.main]]
name = "Archives"
url = "/archives"
weight = 5

#[[languages.zh.menu.main]]
#name = "Search"
#url = "/search/"
#weight = 10

[[languages.zh.menu.main]]
name = "Tags"
url = "/tags"
weight = 20

[outputs]
home = [ "HTML", "RSS", "JSON" ]
[markup]
  [markup.goldmark]
    duplicateResourceFiles = false
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = false
        eastAsianLineBreaksStyle = 'simple'
        enable = false
        escapedSpace = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = false
        [markup.goldmark.extensions.extras.insert]
          enable = false
        [markup.goldmark.extensions.extras.mark]
          enable = false
        [markup.goldmark.extensions.extras.subscript]
          enable = false
        [markup.goldmark.extensions.extras.superscript]
          enable = false
      [markup.goldmark.extensions.passthrough]
        enable = false
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = false
      [markup.goldmark.renderHooks.link]
        enableDefault = false
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
#[markup]
#defaultMarkdownHandler = 'goldmark'
#[markup.goldmark.renderer]
#unsafe = true

#[markup.highlight]
#noClasses = false

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
[params]
env = "production"
description = "This is Kris's neverland"
author = "Kris"
defaultTheme = "auto"
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true

  [params.profileMode]
  enabled = true
  title = "Kris's Neverland"
  #imageUrl = "#"
  #imageTitle = "my image"
  subtitle = "ğŸ˜Welcome to Kris's Neverland!ğŸ«¡"
    [[params.profileMode.buttons]]
    name = "Archives"
    url = "/archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "/tags"

  [params.homeInfoParams]
  Title = "Kris's Neverland"
  Content = """
  ä»Šæœæœ‰é…’ä»Šæœé†‰ï¼Œæ˜æ—¥æ„æ¥æ˜æ—¥æ„ã€‚ğŸ˜\n
  äººç”Ÿå¾—æ„é¡»å°½æ¬¢ï¼Œè«ä½¿é‡‘æ¨½ç©ºå¯¹æœˆã€‚ğŸ«¡
"""

  #[[params.socialIcons]]
  #name = "github"
  #title = "View Source on Github"
  #url = "https://github.com/adityatelange/hugo-PaperMod"

  #[[params.socialIcons]]
  #name = "Discord"
  #title = "Join discord community"
  #url = "https://discord.gg/ahpmTvhVmp"

  #[[params.socialIcons]]
  #name = "X"
  #title = "Share PaperMod on X/Twitter"
  #url = "https://x.com/intent/tweet/?text=Checkout%20Hugo%20PaperMod%20%E2%9C%A8%0AA%20fast,%20clean,%20responsive%20Hugo%20theme.&url=https://github.com/adityatelange/hugo-PaperMod&hashtags=Hugo,PaperMod"

  #[[params.socialIcons]]
  #name = "KoFi"
  #title = "Buy me a Ko-Fi :)"
  #url = "https://ko-fi.com/adityatelange"

  #[params.editPost]
  #URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  #Text = "Suggest Changes"
  #appendFilePath = true

  [params.assets]
  disableHLJS = true